[package]
name = "country_slice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
dolly = "0.3.1" #camera
glam = "0.21.2" #math for dolly, even tho bevy has vecs
bevy_config_cam = "0.3.0" 